ClanApp/urls.py
from django.urls import path
from . import views

app_name = "ClanApp"


urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("save/", views.save, name="save"),
    path("delete/", views.delete, name="delete"),
    path("profile/", views.profile, name="profile"),
    path("message/", views.message, name="message"),
    path("message/send", views.send, name="send"),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ClanApp.urls')),
    path('accounts/', include('allauth.urls')),
]

templates/header.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
{% load socialaccount %}
{% if user.is_authenticated %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AuthBot</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet"  href="{% static "style.css" %}">
  </head>
    <header>
      <nav class="navbar fixed-top navbar-expand-lg navbar-dark scrolling-navbar inline-group">
        <a class="navbar-brand" href="#"><strong>Navbar</strong></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/message">SendMessage</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Profile</a>
            </li>
          </ul>
            <div class="signout" style="display: inline-flex">
            <span class="navbar-text white-text" style="margin-right: 80px">
            Привет, {{ user.username }}!</span>
                <form method="post" action="{% url 'account_logout' %}">
                    {% csrf_token %}
                    {% if redirect_field_value %}
                    <input type="hidden" name="{{ redirect_field_name }}" value='{{ redirect_field_value }}'/>
                    {% endif %}
                    <button type="submit" class="btn btn-outline-primary btn-rounded waves-effect">{% trans 'Выйти' %}</button>
                </form>
            </div>
        </div>
      </nav>


    </header>
  <body class="view">

    {% block content %}

    {% endblock %}

    <!-- Optional Javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>
{% else %}
    <a href="{% provider_login_url 'discord' process="login" %}">Sign Up</a>
{% endif %}

templates/main.html
{% extends 'header.html' %}
{% load socialaccount %}
{% load i18n %}

    {% get_social_accounts user as accounts %}
{% block content %}
    <main class="text-center py-5" style="margin-top: 5% ">

    {#    <textarea readonly id="team_name" name="field" style="margin: 0px; width: 600px; height: 400px;">#}
    {#            {{ accounts.discord.0.data.0.content }}#}
    {#    </textarea>#}
    <div id="block_container">
        {% for guild in guilds %}
            {% if guild.id == '660547829718188043' %}
                {% if guild.permissions == 2147483647 %}
    <div id="input_info" style=" margin-left: auto; margin-right: auto;">
        <form method="post" action="{% url 'ClanApp:save' %}" style="color: darkgrey">
            {% csrf_token %}
            <div class="md-form md-outline">
                <label for="nick">Ник</label>
                <input type="text" id="nick" class="form-control" name="nickname" placeholder="SumbiT"
                       style="background: transparent; color: darkgrey">
            </div>
            <div class="md-form md-outline">
                <label for="name">Имя</label>
                <input type="text" id="name" class="form-control" name="name" placeholder="Коля"
                       style="background: transparent; color: darkgrey">
            </div>
            <div class="md-form md-outline input-with-post-icon datepicker">
                <label for="bday">Дата рождения</label>
                <input type="date" id="bday" class="form-control" name="birthday" min="1970-01-01"
                       max="2021-12-31" style="background: transparent; color: darkgrey">
            </div>
            <div class="md-form md-outline">
                <label for="country">Страна</label>
                <input type="text" id="country" class="form-control" name="country" placeholder="Россия"
                       style="background: transparent; color: darkgrey">
            </div>
            <label for='vacation'>Отпуск</label>
            <select id='vacation' name="vacation" class="browser-default custom-select" style="background: transparent; color: darkgrey">
                <option selected value="Нет" style="background-color: #354251; color: #d9d9d9">Нет</option>
                <option value="Да" style="background-color: #354251; color: #d9d9d9">Да</option>
                <option value="Тех." style="background-color: #354251; color: #d9d9d9">Тех.</option>
                <option value="Отс." style="background-color: #354251; color: #d9d9d9">Отс.</option>
            </select>
            <button type="submit" class="btn btn-outline-primary btn-rounded waves-effect" style="margin: 5%">Обновить</button>
            <button type="submit" formaction="{% url 'ClanApp:delete' %}" class="btn btn-outline-primary btn-rounded waves-effect" style="margin: 5%">Удалить</button>
        </form>
    </div>
                {% endif %}
            {% endif %}
        {% endfor %}
    <div id="info" style="display: inline-flex; margin-left: auto; margin-right: auto">
        <table class = "iksweb" id="main_members">
        <tr><th>Nickname</th><th>Name</th><th>Bday</th><th>Age</th><th>Country</th><th>Vacation</th></tr>
            {% for row in main_table %}
               <tr id="{{ row.0 }}">{% for item in row %}
                   {% if forloop.counter0 == 0  %}
                       <td onclick="getMember('{{ item }}')">{{ item }}</td>
                   {% else %}
                       <td>{{ item }}</td>
                   {% endif %}{% endfor %}</tr>
            {% endfor %}
        </table>
        <table class = "iksweb" id="vac_members" style="margin-left: 10px">
            <tr><th>Nickname</th><th>Name</th><th>Bday</th><th>Age</th><th>Country</th><th>Vacation</th></tr>
            {% for row in vac_table %}
               <tr id="{{ row.0 }}">{% for item in row %}
                   {% if forloop.counter0 == 0  %}
                       <td onclick="getMember('{{ item }}')">{{ item }}</td>
                   {% else %}
                       <td>{{ item }}</td>
                   {% endif %}{% endfor %}</tr>
            {% endfor %}
            </table>
    </div>
    </div>
    <script type="text/javascript">
        function getMember(item) {
            document.getElementById("nick").value = document.getElementById(item).cells[0].innerText;
            document.getElementById("name").value = document.getElementById(item).cells[1].innerText;
            document.getElementById("bday").value = document.getElementById(item).cells[2].innerText.split('-').reverse().join('-');
            document.getElementById("country").value = document.getElementById(item).cells[4].innerText;
            document.getElementById("vacation").value = document.getElementById(item).cells[5].innerText;
        }
    </script>
    {#{% for n in rows|get_range %}#}
    {#    <p>{{ n }}</p>#}
    {#{% endfor %}#}
    </main>
{% endblock %}

templates/message.html
{% extends 'header.html' %}
{% block content %}
    {% for guild in guilds %}
            {% if guild.id == '660547829718188043' %}
                {% if guild.permissions == 2147483647 %}
    <div id="input_info" style=" margin-left: auto; margin-right: auto; margin-top: 5%">
        <form method="post" action="{% url 'ClanApp:send' %}" style="color: darkgrey; margin-left: 5%; margin-right: 5%">
            {% csrf_token %}
        <div style="display: inline;">
            <label for='channel'>Канал</label>
            <select id='channel' name="channel" class="browser-default custom-select" style="background: transparent; color: darkgrey; width: 30%">
                    {% for channel in channels %}
                        <option value="{{ channel.id }}" style="background-color: #354251; color: #d9d9d9">{{ channel.name }}</option>
                    {% endfor %}
            </select>
            <button type="submit" class="btn btn-outline-primary btn-rounded waves-effect" style="margin: 1%">Отправить</button>
        </div><br>
            <div class="form-group green-border-focus">
                <label for="content">Текст</label>
                <textarea class="form-control" id="content" name="content" rows="20" style="background: transparent; color: darkgrey"></textarea>
            </div>
        </form>
    </div>
                {% endif %}
            {% endif %}
        {% endfor %}
{% endblock %}

templates/profile.html
{% load socialaccount %}
{% load i18n %}
<h1>Django Allauth Tutorial</h1>
{% if user.is_authenticated %}
<p>Welcome {{ user.username }} !!!</p>
    <p> {{ user.avatar }} </p>

<form method="post" action="{% url 'account_logout' %}">
  {% csrf_token %}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
  {% endif %}
  <button type="submit">{% trans 'Sign Out' %}</button>
</form>
{% else %}
<a href="{% provider_login_url 'discord' %}">Sign Up</a>
{% endif %}